drop database if exists ecommerce;
create database ecommerce;
use ecommerce;


create table users(
	user_id serial primary key,
	username varchar(100),
	email varchar(255),
    firstname varchar(100),
    lastname varchar(100),
	password varchar(100),
	secret_question varchar(200),
	secret_question_answer varchar(200),
	reg_date datetime
);

create table products(
	product_id serial primary key,
	productName text,
	productBrand text,
	productDescription text, 
	productPrice text,
	ProductImage text 
);

INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Shirt', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$220', 'tut/img/products/f1.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Shirt', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$220', 'tut/img/products/f2.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Shirt', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$220', 'tut/img/products/f3.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Shirt', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$220', 'tut/img/products/f4.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Shirt', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$220', 'tut/img/products/f5.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Jacket', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$180', 'tut/img/products/f6.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Pants', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$80', 'tut/img/products/f7.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Long Sleeve', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$120', 'tut/img/products/f8.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Long Sleeve', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$120', 'tut/img/products/f9.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Long Sleeve', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$120', 'tut/img/products/f10.jpg');

INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Long Sleeve', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$120', 'tut/img/products/f11.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Short Sleeve', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$230', 'tut/img/products/f12.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Long Sleeve', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$120', 'tut/img/products/f13.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Shorts', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$120', 'tut/img/products/f14.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Jacket', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$180', 'tut/img/products/f15.jpg');
INSERT INTO `products` (`product_id`, `productName`, `productBrand`, `productDescription`, `productPrice`, `ProductImage`) VALUES (NULL, 'Short Sleeve', 'Nike', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut urna pellentesque, tempus libero at, blandit velit. Sed dignissim nisl at fermentum semper. Nulla ac justo dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis porta dapibus. Etiam nulla felis, ultricies nec justo ultricies, feugiat tempor dui. Donec at nulla eu velit vestibulum eleifend a quis odio. Nunc eget accumsan odio, et aliquet nulla. Phasellus eleifend, quam eu lacinia euismod, massa elit tristique elit, nec pharetra erat lorem et leo. Phasellus lobortis luctus tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus vestibulum enim a turpis tristique, id hendrerit risus convallis.', '$230', 'tut/img/products/f16.jpg');



